### ISSUE TITLE
Cannot see synced files in Files app

### ISSUE THREAD

**Issue by jonathan-kosgei** [MobiusSync/MobiusSync#101]
I've tried to sync multiple folders between my laptop and ipad and mobius sync does not create any folders as far as I can see in the Files app. I've clicked on "Open Folders" multiple times but it just opens the Files app homepage.

Note that when I create a file on the laptop and rescan I can see the Latest Change in mobius correctly show the name of the file I created. I just can't find it anywhere.

**Comment by SimonPickup** [comment]
There should be a folder named "Möbius Sync" created under "On My iPhone". Somebody has previously reported that it only appear in the Files app after restarting their phone. Please see if that helps in your case.

**Comment by SimonPickup** [comment]
Some suggested steps here also: #83

**Comment by rasa** [comment]
On your iPad, the folder will be named "On My iPad":
![D1D04D56-B714-4046-9CBD-D0C939DC1A45](https://user-images.githubusercontent.com/220772/219714638-dda88a34-9a2b-4ddc-8b1f-1327c270a395.jpeg)

**Comment by jonathan-kosgei** [comment]
@sjpickup you were right, after restarting the Mobius directory appeared! Thanks!
