### ISSUE TITLE
Basic shortcuts API

### ISSUE THREAD

**Issue by Sakooooo** [MobiusSync/MobiusSync#107]
Please try to implement a simple shortcuts API as I want to Sync when I open an app, thanks!

**Comment by SimonPickup** [comment]
Thanks for the idea. I have never looked into this. I'm not sure if the Shortcuts API can trigger a background activity.

**Comment by Sakooooo** [comment]
if you go into the shortcuts app > automations, you can make it so whenever you plug it into charger, battery is low, low power mode, open an app, turn on airplane mode and etc you can even make it choose a random time for it its not fully background sync but its something that could work 🤷

**Comment by SimonPickup** [comment]
You can already create a shortcut to open any app (including MobiusSync) in the foreground.

So it's only background that you are requesting?

(It looks like iOS limits background activities triggered from Siri Intents to only 30s anyway, equivalent of the existing scheduled 30s _quick sync_).

**Comment by Sakooooo** [comment]
something like that but that works too, thanks!
