### ISSUE TITLE
Notification to prompt reopening app to continue sync

### ISSUE THREAD

**Issue by sjpickup** [MobiusSync/MobiusSync#11]
Since iOS suspends execution of a process (currently around 30 seconds) after going into the background, Syncthing may still be syncing at such time. It could send a local notification to the user to prompt them to reopen the app if they wish to resume the current sync.

**Comment by YellowSloth** [comment]
(At the time of writing this ticket the initial issue contains a placeholder)

I assume this ticket is about the fact that iOS closes background applications after 2-3 minutes. I'm not sure what the added benefit would be for a reminder to sync. I do would like the files to be synced automatically naturally.

Would it be possible to have a FileProvider which upon requesting a file connects to SyncThing in the backend? With OneDrive and such I often need to wait for the remote files to be gathered, maybe it's possible for MobiusSync to have something similar. 

https://developer.apple.com/documentation/fileprovider?language=objc

**Comment by sjpickup** [comment]
> Would it be possible to have a FileProvider which upon requesting a file connects to SyncThing in the backend? With OneDrive and such I often need to wait for the remote files to be gathered, maybe it's possible for MobiusSync to have something similar.

FileProvider would be the mechanism for implementing Issue #5, but I don't believe it will help with any background activity.

**Comment by sjpickup** [comment]
This is being added in v1.2.

Note (particularly for those concerned about privacy) that the notifications sent are all **local** and no external server is involved.

**Comment by sjpickup** [comment]
Released in v1.2.
