### ISSUE TITLE
App crashes when toggling low power mode

### ISSUE THREAD

**Issue by GilgameshxZero** [MobiusSync/MobiusSync#110]
Observed on Mobius 1.23.2, iOS 16.4, iPhone 12 Mini, when low power mode is triggered manually or via automation.

The app definitely crashes if it in the foreground, and I believe it crashes when in the background as well. I have 0 as the minimum interval between quick syncs, and 5 as the minimum interval between power syncs.

Happy to provide more info/testing if necessary.

**Comment by SimonPickup** [comment]
Great find, thank you. This may explain the occasional background crashes we've seen. I can reproduce this, at least in the foreground. Will advise if any further testing needed.

**Comment by SimonPickup** [comment]
Fix will be in v1.27.7.
