### ISSUE TITLE
MobiusSync selects wrong folder when creating a new share

### ISSUE THREAD

**Issue by andreasscherbaum** [MobiusSync/MobiusSync#111]
Trying to setup MöbiusSync (v1.23.2-41, Build 202303072020) on an iPad to sync Obsidian with Linux. For the tests I had to remove the share again, and then was no longer able to setup a sync for the same directory. Instead MöbiusSync seems to fall back to it's own directory.

Steps to reproduce:
* Create a folder (any folder) in a Obsidian vault
* Add this folder as shared folder in MöbiusSync
* Observe that the content will be synced to the remote system, even new files and any changes
* Remove the Share
* Add the same directory again in a new Share
* Observe that the remove system now sees the default MöbiusSync folder (there are two folders `Sync` and `Obsidian` in this folder, which are empty)

I can reproduce that I can always add a new folder the first time, and then never again. The second attempt to share this folder, as well as any subsequent attempt, MöbiusSync happily accepts the folder, then shows a `bookmark` entry as directory, and always uses the default folder.

Updated example:

* Add a folder (any folder) for the first time in MöbiusSync on iPad, and share it with another system
* In my example and in my test I selected the Obsidian vault folder on the iPad, and the files and folders got synced to the other system. For this I used the option to select an external folder, which is only available in the paid version (which I have).
* The folder gets synced to the remote systems, the content of the folder appears on the remote system
* The remote system (the one this is shared with) is Linux

So far everything is working up to here.

* I removed this Share, because I wanted to document the steps for future usage and the first attempt was just a test
* Side note: on the remote Linux system I wiped the entire folder I used to sync, to make sure there are no stale files - this step happened after the Share was removed on both sides

Then I repeat the steps above:

* On the iPad I select the Obsidian vault folder as directory
* I share this with the remote Linux system

Now I no longer see the Obsidian files synced, but the files which are in the internal MöbiusSync folder - the one you can see when the paid option is not available. I can repeat this step: remove the sync, add it again, same result.

When I instead select a folder which was never synced before, MöbiusSync will select the correct folder and sync the folder content. For this to test, I created sub directories in the Obsidian vault, and selected only this sub directory. Sync works. When I remove the Share, and add the same sub directory again, MöbiusSync falls back to the internal folder.

Which puts me into the unfortunate situation that I can make this work the first time, except not on this device because my goal is to sync the Obsidian vault folder - which was already selected before.

**Comment by SimonPickup** [comment]
Thanks for the detailed list of steps to reproduce, however I don't quite understand the sequence. Can you please update to confirm which device you are doing each step on (iOS or Linux) and when adding the share, which end(s) you are removing and creating the share on first.

**Comment by andreasscherbaum** [comment]
@sjpickup I updated the Issue with more examples. Does this make the situation more clear?

**Comment by SimonPickup** [comment]
OK, I have reproduced this, thanks so much. Will investigate further and provide a workaround if possible and a bug fix.

**Comment by SimonPickup** [comment]
As a workaround, deleting the MöbiusSync app and reinstalling, then recreating your device and folder setup will work.

**Comment by andreasscherbaum** [comment]
It's not yet "in production" here, was a first test before I roll this out to more devices. Can keep this open in case you need a confirmation once a bugfix is implemented.

**Comment by andreasscherbaum** [comment]
Can confirm that uninstalling the app and reinstalling it gives the user "one more shot" at getting it right.
One however has to know this.

**Comment by SimonPickup** [comment]
Fix is now in TestFlight (see #156). Please feel free to test.

**Comment by andreasscherbaum** [comment]
I unfortunately do not have access to an iPad now, which I can test. It's locked in the school network and I can't install apps.
