### ISSUE TITLE
Unable to set "use TLS" to true

### ISSUE THREAD

**Issue by ProbablyPinata** [MobiusSync/MobiusSync#113]
I have tried to set the `use TLS` boolean setting under the advanced settings tab to `true`. However, when I choose to save my updated settings I get the following error message:

> Connection Error: Syncthing seems to be experiencing a problem processing your request. Please refresh the page or restart Syncthing if the problem persists.

Behind the error message I can also see the yellow dev banner, that has the following message:

> Notice: 
> [timestamp] : Decoding posted
> config: json: cannot unmarshal string into Go struct field
> GuiConfiguration.gui.useTLS of type Bool

I could just be doing something wrong, but I've tried some other inputs (including  `True` and `"true"` and  `1`) but none of these seem to work.

How does one go about changing this setting, or is it not possible using Mobius?

**Comment by SimonPickup** [comment]
This setting is not relevant to MobiusSync as it uses a different mechanism to communicate between GUI and Syncthing backend.

There are a number of settings in Advanced which are not relevant to MobiusSync.
