### ISSUE TITLE
App badge showing 1 notification, but no messages inside app

### ISSUE THREAD

**Issue by dorianfm** [MobiusSync/MobiusSync#125]
I've just started using mobius sync, and it shows all files as synchronized, but persistently has a '1' badgebon the icon, with no recent in ios notifications and nothing apparent within the app.

I've turned off notifications for quick sync and power sync in the ios settings as they were quite annoying, and hope this would resolve it.

I can't see anything relevant in the logs - is ther somewhere specific i should be looking fir the source of this badge?

**Comment by SimonPickup** [comment]
I am adding some more aggressive code to clear the badge count. Will be added in 1.27.7.

**Comment by SimonPickup** [comment]
Fix is now in TestFlight (see #156). Please feel free to test.
