### ISSUE TITLE
Not Available in Spanish App Store

### ISSUE THREAD

**Issue by jalberto** [MobiusSync/MobiusSync#128]
Hi, I will love to try your app, but I cannot find it in the Spanish App Store.

Any possibility you enable it for Spain?

Thanks

**Comment by pjerem** [comment]
It's the same in France. I'd happily use it otherwise.

**Comment by jalberto** [comment]
@SimonPickup anything we can do to help with this issue?

**Comment by SimonPickup** [comment]
France is the only country we have deliberately excluded: https://github.com/MobiusSync/MobiusSync/issues/27

Seems to be available in Spain: https://apps.apple.com/es/app/möbius-sync/id1539203216
