### ISSUE TITLE
Original File Creation Date Modified After Sync

### ISSUE THREAD

**Issue by kennygokh** [MobiusSync/MobiusSync#130]
A file was created on 03-Nov-23, see screenshot highlighted in red box. I did a simple update to this file, and you can see modified date shown today date & time (05-Nov-23 11:45). However, when I sync from MacBook to iPhone, the creation date was modified as today's date. Any idea how to prevent from changing as I need to preserve the file creation date for other purpose. Please advise.

MacOS Screenshot:
<img width="1084" alt="image" src="https://github.com/MobiusSync/MobiusSync/assets/97268671/1dd12129-786a-4a9d-a708-47907a94845c">

iPhone Screenshot:
<img width="1103" alt="image" src="https://github.com/MobiusSync/MobiusSync/assets/97268671/b2657d2a-7156-473e-9cfc-65d18ca70e82">

**Comment by rasa** [comment]
This is not a Mobius issue, as Syncthing itself doesn't sync any dates other than the modification time (i.e., accessed, changed, and created/birth). See https://docs.syncthing.net/users/faq.html#what-things-are-synced
