### ISSUE TITLE
Support for Apple Vision Pro

### ISSUE THREAD

**Issue by yingzhu146** [MobiusSync/MobiusSync#141]
It seems that the apple vision pro is currently not supported. I assume there are technical reasons for this, but at least to express user interest I'm filing this issue. As the premiere apple media device of course it would  be great to sync my study/work related files (e.g. lectures, papers, etc.) to it

**Comment by dannyob** [comment]
If it’s just a matter of flipping the bit that says that the AVP is supported, please go ahead and do that!

**Comment by SimonPickup** [comment]
I don't have access to an Apple Vision Pro to test, but we will enable through TestFlight: https://github.com/MobiusSync/MobiusSync/discussions/156
