### ISSUE TITLE
Open Files App/Open Folder buttons do nothing, “Unsupported folder” when trying to add external folder on iOS 17

### ISSUE THREAD

**Issue by greyivy** [MobiusSync/MobiusSync#142]
I’m not able to access any files synced by this app, sandboxed or otherwise. 

iOS 17.3.1

**Comment by Radieserlbrot** [comment]
I am on iOS 17.4 and also have this problem with an external folder. Can anyone help how to circumvent this issue?
Thanks a lot

**Comment by kahilah** [comment]
Also experiencing this when trying to choose a folder from icloud section of directory structure. OneDrive is greyed out which I presume is due to App restrictions?

**Comment by SimonPickup** [comment]
Mobius Sync only supports external folders under "On My iPhone", not files under other file provider locations like iCloud Drive or Dropbox etc.

If you are having problems with other folders, please try to reproduce on the latest TestFlight beta (see #156) and raise as a new issue.
