### ISSUE TITLE
Not possible to open external folders in iPad OS 17 - “Couldn’t communicate with helper application.”

### ISSUE THREAD

**Issue by kraniumet** [MobiusSync/MobiusSync#143]
Hello!
Since updating to iPad OS17, I can no longer add external folders from other apps sandboxes. The error displays like this:
![IMG_7277](https://github.com/MobiusSync/MobiusSync/assets/82153552/91686c96-cb4c-4fa2-b26a-d3b75f1ad21d)

Old folders previously added still sync like they should.

**Comment by SimonPickup** [comment]
Is this still happening? Please try to reproduce on the latest TestFlight beta (see #156).

**Comment by SimonPickup** [comment]
Please reopen if this is still happening.
