### ISSUE TITLE
Incorporate Syncthing v1.27.7

### ISSUE THREAD

**Issue by aliaksandrsen** [MobiusSync/MobiusSync#146]
Could you please update MobiusSync to the latest SyncThing version?

**Comment by Radieserlbrot** [comment]
Yes, I would also very much appreciate this. I have bought the Pro Version, too

**Comment by SimonPickup** [comment]
This is in progress.

**Comment by egigoka** [comment]
> This is in progress.

Oh, thanks. I've thought app is no longer supported 😥

If you need an subscription for stable development, please do. Dollar a month is alright.

**Comment by gaydenko** [comment]
> This is in progress

Oh, I have found  this issue and immediately have bought a pro in the App Store. Thanks for reviving the app and good luck with the implementation.

**Comment by AcaDemIQ** [comment]
@SimonPickup 

Hello, the new version of the Syncthing is v1.27.6

**Comment by SimonPickup** [comment]
Will be updated to the latest at the time when ready for release.

**Comment by SimonPickup** [comment]
This is now in TestFlight (see #156). Please feel free to test.
