### ISSUE TITLE
Files app broken in iOS 17.4

### ISSUE THREAD

**Issue by pax0707** [MobiusSync/MobiusSync#150]
After installing it and setting up sync on iPhone 14 Pro Max on iOS 17.4.1 the Files app started behaving erratically. Nonresponsiveness, could not open folders and after some time it froze the device. 
Had to do a force restart of the whole device.
After removing the app and restarting the device everything went back to normal.

**Comment by Petemir** [comment]
Having the same problem on an iPhone 12, iOS 17.4.1. Every now and then a reboot of the phone is needed.  Given the amout of people sharing the problem [here](https://old.reddit.com/r/ios/comments/1bh10u2/files_app_freezing_also_in_thirdparty_apps_in_ios/), I wouldn't expect it to be just a MobiusSync issue.

**Comment by SimonPickup** [comment]
Appears to be fixed in iOS 17.5.
