### ISSUE TITLE
Default Folder Path of ~ no longer works

### ISSUE THREAD

**Issue by egigoka** [MobiusSync/MobiusSync#165]
iOS version: 17.5.1
Device: iPhone 11 Pro Max
Möbius Syncthing version: v1.27.7-163-g1733568b0-i, iOS (64-bit ARM)
Möbius version: Version 1.27.7 (202405310620)

STR:
1) create folder on another Syncthing node
2) share it to iOS node
3) accept shared folder on iOS device
4) get error: 

```
2024-06-14 18:19:26: Failed to create folder root directory mkdir /private/var/mobile/Containers/Data/Application/E198FB3B-C201-47CA-BDC0-06D4432867EA/TheVolgun: operation not permitted

2024-06-14 18:19:26: Error on folder "TheVolgun" (rgakx-ntx9r) at ~/TheVolgun: folder path missing
```

Expected result:
Folder created and syncing

Experienced result:
Folder errors out while creating

**Comment by SimonPickup** [comment]
Thanks for the detailed information. Can you please send a screenshot of the Edit Folder window.

**Comment by egigoka** [comment]
No problem 
![image](https://github.com/MobiusSync/MobiusSync/assets/23525323/6cce553b-6574-403b-97ab-0180067892d5)
![image](https://github.com/MobiusSync/MobiusSync/assets/23525323/12187359-2905-4828-80a7-a2148c20a08a)

**Comment by SimonPickup** [comment]
Thanks. When you accept the share offer, the Folder Path should default to just the folder label, i.e. "TheVolgun", but you have "~/TheVolgun".

Can you try again and let me know whether the suggested default Folder Path contains a the ~/ prefix?

Also, is this an TestFlight installation over an earlier version or did you delete and reinstall afresh?

**Comment by egigoka** [comment]
I can send you logs, just don't want to show my IP's to all GitHub to witness. If you need them, give me your contact information.

**Comment by SimonPickup** [comment]
Also, what is your default Folder Path (visible under Actions/Settings/General/Edit Folder Defaults.

It should be blank. Maybe for you it is ~ ?

**Comment by egigoka** [comment]
It's indeed "~". Maybe default from previous versions. I didn't do clean install and just upgraded through years including TestFlight version. 

![image](https://github.com/MobiusSync/MobiusSync/assets/23525323/588556a0-1114-4372-b072-7526a84fdf81)

**Comment by SimonPickup** [comment]
Great, so I need to do some db migration for upgrading users. Thanks for finding this.

I preusme if you manually change to blank it will work now?

**Comment by egigoka** [comment]
Should I do clean install? I don't look up to it, bc, firstly, it's a valid use case to just update app from AppStore and don't reinstall it and, secondly, it's re-sharing all folders :D

**Comment by egigoka** [comment]
> Great, so I need to do some db migration for upgrading users. Thanks for finding this.
> 
> 
> 
> I preusme if you manually change to blank it will work now?

I'll try to change folder default path, re-share and follow up here how it goes

**Comment by egigoka** [comment]
It's started syncing, but shows double size, folders count and files count in Global state compared to my Linux server. I'll write here when it finishes.

**Comment by SimonPickup** [comment]
OK, I have confirmed this was introduced in my changes for 1.27.7 for upgrading users, and I have a fix in place. Waiting for Apple approval of 1.27.8 TestFlight, then I'll share the fix on TestFlight.

**Comment by SimonPickup** [comment]
Fix now available in TestFlight. For more info, see https://github.com/MobiusSync/MobiusSync/discussions/156
