### ISSUE TITLE
Flickering display when app reopened 

### ISSUE THREAD

**Issue by SimonPickup** [MobiusSync/MobiusSync#177]
From https://www.reddit.com/r/Syncthing/comments/1e0kydt/mobius_on_ios/

Sometimes when returning to the app, the GUI flickers repeatedly.

https://github.com/user-attachments/assets/08002062-06cb-4266-9ccb-997de1763b29

**Comment by SimonPickup** [comment]
I have seen this too. My guess is there are queued update events that all get procesed once the app returns to the foreground.

**Comment by kwlorenz** [comment]
Same problem here, have to close and reopen the app. Can be provoked when pulling down to refresh

**Comment by zardozerr** [comment]
I can confirm that I get this weird flickering problem. It's not just cosmetic; the app actually won't work properly. The only way to resolve it is to force quit the app and reload it. This happens on both an iPhone and an iPad Pro.

**Comment by DR-D-RGB** [comment]
I am experiencing this regularly on my ipad. Happens when I reopen app after a period of inactivity. I thought this could be due to a lot of pending sync attempts and iOS queueing them. So I turned off background sync to once once in a day, it still does the flickering. One time it legit freezed by ipad and I wasn't even able to go back to home screen to kill it for a while

**Comment by mgruca** [comment]
I get that as well. I'm just after the last update and it feels like it happens whenever I get back to the app

**Comment by cakeller98** [comment]
yep, I'm having this problem too.

im on iphone and when i open it its not flickering its jumping home and back and to the end etc.

hard closing the app and reopening definitely fixes the display glitch.

**Comment by rotbaer-peter** [comment]
I have this problem too (iPad pro 2024, iPhone 14pro).

**Comment by SimonPickup** [comment]
Actually I think I fixed this variant of the bug in earlier TestFlight build: see #194 if you want to test it out

**Comment by rotbaer-peter** [comment]
Thank you, I just installed the Test Flight Build and this bug seems to be solved. If it returns, I will give you feedback!

**Comment by rotbaer-peter** [comment]
It's still there with the actual TestFlight build 1.27.10 (202409211850)

**Comment by bartekbiz** [comment]
Hi, when this fix is going to be on AppStore?

**Comment by SimonPickup** [comment]
Should be a matter of days, it with Apple for review.
