### ISSUE TITLE
Photo Collection folder options - toggle photos/videos/live photos

### ISSUE THREAD

**Issue by SimonPickup** [MobiusSync/MobiusSync#178]
Add a _Photo Collection_ tab to Folder Options and add toggles:

- Include photos
- Include videos
- Include Live Photos as photos
- Include Live Photos as videos

Changed options will be applied on next scan, which can be manually triggered by _Rescan_ button

**Comment by SimonPickup** [comment]
Now available in TestFight: https://github.com/MobiusSync/MobiusSync/discussions/194.

**Comment by andreasnyc** [comment]
Thanks @SimonPickup! Is there any documentation as to what these last 3 mean ( Include live Photos as photos; Include Live Photos as videos; Include edited form)?
I checked the FAQ on mobiussync.com. If one wants still photos as such, videos as such, and  Live Photos files to stay intact as .heic (or .jpg) including the video data, which would one choose?

Current version has
- Include photos
- Include videos
- Include live Photos as photos
- Include Live Photos as videos
- Include edited form
