### ISSUE TITLE
Photo Collection folder options - set timezone for file stamping

### ISSUE THREAD

**Issue by SimonPickup** [MobiusSync/MobiusSync#180]
When syncing photos/videos in a _Photo Collection_ folder, the filename exposed to syncthing peers inlcudes the timezone represented in "local time". If a user changes their phone's timezone, e.g. when travelling, this would **rename** all the exported filenames.

Thus when a _Photo Collection_ folder is created, the current device's timezone is captured, but configurable if the user wishes to override.

Options changes apply on a (re)scan.

**Comment by mjraneri** [comment]
Is it possible to use the photo’s “date captured”?

**Comment by SimonPickup** [comment]
> Is it possible to use the photo’s “date captured”?

Do you have examples where it is not?

**Comment by SimonPickup** [comment]
Now available in TestFight: https://github.com/MobiusSync/MobiusSync/discussions/194.
