### ISSUE TITLE
Photo Collection - All items erroneously duplicated

### ISSUE THREAD

**Issue by mjraneri** [MobiusSync/MobiusSync#187]
I have been using the new version and syncing with my photo collection for one or two weeks. This is a great capability.  However this weekend I captured perhaps another 150 still images and a few videos, and when I opened sync I expected the rescan to just capture those additional images.  However the rescan rescanned my whole library as if all the images were duplicated. I have about 6800 images and 44GB in total, but möbius sync now shows 12,700 images and 80GB. This is not correct.  I don’t know what is happening on the receiving end because I’m not at home to view, and the sync will take a long time (to upload 35GB over a slow connection.

something is wrong.
(I’m using the paid app, not the in app purchase version)

![IMG_3099](https://github.com/user-attachments/assets/7631c5c5-bdb3-4c45-88b2-5a56bfce98b7)
![IMG_3098](https://github.com/user-attachments/assets/6295757c-9090-4caf-8ce5-48bf43784cac)

**Comment by mjraneri** [comment]
Ok here's the issue.  Since the last time I synced, I've traveled to a different timezone.  So all the images now have duplicates with different names due to the 3 hour time zone change:

![image](https://github.com/user-attachments/assets/82a137af-eaf4-4469-a70b-3ff898976e8e)

I don't understand why the images were "duplicated".  I would have understood if all the files were "renamed".  But they weren't.  Anyway, even if they were renamed, this is still wrong.  (Most of the images are not being transferred, they are just being recopied based on the hashes, so the sync is fast, but now I have double the number of images I should have.

Files should have timestamps based on the timezone stored in the photo, not the current time zone of the phone.  I guess I'll wait until I get home and see what happens.

**Comment by SimonPickup** [comment]
This is being addressed in #180. Thanks for your detailed reporting. I understand Syncthing doesn't always do renames gracefully, but I think once the sync completes it should sort itself out.

**Comment by mjraneri** [comment]
FYI the sync completed and while I DO have the receiving folder “send and receive” I do have duplicates of all the previously transferred images. 

This is also demonstrated in the folder state image above showing >12000 images in the global and local state when the camera roll only has 6800.

it’s almost like whatever database you are using to keep track of the link between the images in the camera roll and the files in syncthing now has duplicated entries with two entries per image, both pointing to the same image.

multiple separate connections and rescans has not resolved this duplication.

**Comment by SimonPickup** [comment]
Thanks for the update. A new version with fix will be out in TestFlight shortly.
