### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by metbril** [MobiusSync/MobiusSync#193]
When I let Mobius run in the background for a while, it starts flickering. See movie. I'm not sure if syncing still works.  It i can't use the app then. 

I can force kill the app and open again. 

https://github.com/user-attachments/assets/fb911f96-609b-48e6-9deb-b6f5e6250f60

**Comment by metbril** [comment]
Duplicate of #177?

**Comment by rasa** [comment]
> Duplicate of #177?

I see this too, and it's not really #177, as the template vars are seen flickering here, but not in #177, so I would say this issue better describes the problem.

**Comment by SimonPickup** [comment]
I fixed a javascript merge issue, that hopefully resolves. Will be out in TestFlight soon.

**Comment by metbril** [comment]
Thanks for addressing this. I don't use TestFlight myself. What is the expected regular release date?

**Comment by whatjakecodes** [comment]
I am also having this issue and curious if there is a release planned. I just started using MobiusSync and this behavior has me wondering if it is syncing properly or breaking down.

**Comment by SimonPickup** [comment]
Now available in TestFight: https://github.com/MobiusSync/MobiusSync/discussions/194.

**Comment by SimonPickup** [comment]
I saw this again after I thought I'd fixed it. I think my earlier fix dealt with #177.

However I do now I have a proper fix for this one, coming to TestFlight soon.

**Comment by kwlorenz** [comment]
I do not use TestFlight die to produktive Environment. Bug is really annoying. Seems to appear, when app wakes up from sleep/hibernation and tries to start a sync.
When will anfix be available?

**Comment by thearthur** [comment]
I am also seeing this

**Comment by SimonPickup** [comment]
New fix in TestFight: https://github.com/MobiusSync/MobiusSync/discussions/194.

**Comment by rotbaer-peter** [comment]
App „freezes“ when reopened after some time (only on iPad Pro 2024 / M4, not on iPhone).
![IMG_9353](https://github.com/user-attachments/assets/2e7d136b-28c5-4801-a7e8-8ab2311d6b10)
