### ISSUE TITLE
[META] TestFlight or GA?

### ISSUE THREAD

**Issue by scuba-tech** [MobiusSync/MobiusSync#2]
Hello! Not an issue with the app, moreso an issue/question about my contribution:

I see that app is now GA on the App Store (congrats!!)

Currently, I’m enrolled in Test Flight through my participation on the Syncthing forum and running the latest version of (1.0 202011111106). 

Does my Test Flight enrollment allow me to continue beta-testing to help out, or do I need to switch Test Flight channels to the GA beta, or must I switch to the GA main release?

(I don’t mind paying! Just want to know what makes the greatest beneficial impact)

**Comment by sjpickup** [comment]
Thanks for the lovely feedback and support.

We'll eventually remove the TestFlight versions, but didn't want to push those who helped us out onto a paying version too quickly. Best functional benefit to you and to us in terms of feedback will be on the latest public release at this stage.

We may push new beta versions to TestFlight in future when there are significant changes in the pipeline, so stay tuned.
