### ISSUE TITLE
UI: improve on native iOS design

### ISSUE THREAD

**Issue by ivankovnatsky** [MobiusSync/MobiusSync#20]
i'm not a big export in iOS, but it seems like you're running a web server of syncthing and the app loads the web page of it, please correct me if i'm wrong.

any plans to use iOS native design patterns within the app?

**Comment by sjpickup** [comment]
Using the existing Syncthing web interface inside the iOS app was chosen for a few reasons:
1. It helped us get off the ground quicker.
2. It will help us keep up with new releases to Syncthing along the way.
3. We expect the vast majority of our users will be using Syncthing on other platforms also, so consistency of look-and-feel should reduce friction.

Is there anything in particular you're looking for in iOS design that you think would improve usability?

**Comment by ivankovnatsky** [comment]
i personally find it very much usable, but since it's an app, i thought maybe someone could come up with native UI that could be even better (as might be Apollo for Reddit). i myself not a designer or so, just my thoughts.

**Comment by YellowSloth** [comment]
For me it's function over form. I wouldn't mind if the interface stays exactly like it is now.
