### ISSUE TITLE
Mobius sync incorrectly calculates free space. Stops folder.

### ISSUE THREAD

**Issue by mjraneri** [MobiusSync/MobiusSync#202]
Mobius sync has “stopped” a folder because there’s not enough room for the database, but there’s plenty of space.  This has been happening more frequently.  It would also be nice to be able to wipe the database without having to delete the app, reinstall, and reconnect all the devices and folders if the database is growing in size and needs to be “cleaned up”.
![IMG_9418](https://github.com/user-attachments/assets/4fa5ecc4-5c39-4506-bafc-7e6c451223a4)
![IMG_9419](https://github.com/user-attachments/assets/072f561c-07a3-4952-aca6-07d920540316)

**Comment by SimonPickup** [comment]
See #17 re disk space checks.

Re the database growing, seems to be a common syncthing upstream problem.
