### ISSUE TITLE
Restore Versions - Tapping on folder caused non-responding

### ISSUE THREAD

**Issue by jaydonteh** [MobiusSync/MobiusSync#35]
Tapping on the folder or the mass actions drop-down menu causes the app to hang but not crash. It would be non-responding until you force close through iOS Recently Used Apps.

Affected devices:
- iPhone 11
- iPad mini

**Comment by sjpickup** [comment]
This doesn't happen on my devices, obviously. What can be special about yours? What iOS version? Is this on first install or after setting up? What folders do you have?

**Comment by jaydonteh** [comment]
> This doesn't happen on my devices, obviously. What can be special about yours? What iOS version? Is this on first install or after setting up? What folders do you have?

I'm on 14.4 iOS. I've been using Möbius Sync since it's release. Never really tried tinkering on versioning until today. Tried making some edits to see if it works and sure enough it does show a recent version after the change on my pc. But it just goes non-responding once I tap on the folder or the mass actions.

I assumed it was the app as it did occur on both my iPhone and my iPad mini. My setup is straightforward similar to what's on default and uses simple file versioning.

I'm quite new to this so I might have missed some crucial settings.

**Comment by chluna** [comment]
I am experiencing the same issue on my iOS devices. I am using the latest version of Mobius Sync (but on a free tier), with everything excluded from the main Syncthing peer using `.stignore`, except for 5 files in 5 folders that I want to sync locally. I set versioning to staggered with a 90 day maximum age for the local folder.

I am running the following devices with this issue:

- iPhone 12 mini (iOS 14.4.2)
- iPad mini 5 (iOS 14.4.1)

**Comment by SimonPickup** [comment]
Closing this stale issue. Of course re-open if anyone is still seeing this.
