### ISSUE TITLE
Photo upload

### ISSUE THREAD

**Issue by spiff72** [MobiusSync/MobiusSync#4]
Hello,

I just found this app this morning, which got me very excited for future possibilities.  I would like to say that having a way to do a photo sync (one-way) to my Syncthing "server" would be a killer app feature.  I don't like dealing with iCloud if I don't have to.

I just bought a new iPhone after spending 10 years on Android, and the Syncthing app is the ONE thing that I miss the most.  All I used it for on Android phones was to sync photos that I take with my phone to the syncthing server so that they then show up on all my PCs for use (emailing, editing, etc).  The one-way only setup is not an issue for me at all.  So if background sync was possible, this would make it a "killer app" for me immediately.  

If this is enhanced in the future I will be first in line to buy the premium version!

**Comment by sjpickup** [comment]
Thanks for logging this and for your support. I'm looking forward to getting photo upload working too!

**Comment by sjpickup** [comment]
One of the choices to made when implementing this feature is whether files should be sent as-is (e.g. live photos HEIC/MOV formar) or converted to another format (or ideally configurable).

**Comment by spiff72** [comment]
My personal use case is that I don't like to use the HEIC format, so I have my camera set up to keep them in the more compatible JPG format.  I also turned off live photos so I don't get the extra MOV files that go along with that feature.  So the 'as-is' approach would be fine with me.  If this was configurable that could be a plus, but I wouldn't overcomplicate it to start.

**Comment by n8foo** [comment]
I'd like to cast a vote for this feature as well. And I support 'as-is' transfer, especially if that makes the development easier. Also, I just paid for the premium version! Great app!

**Comment by jdarpinian** [comment]
Yeah no need to convert the files, you can choose to disable heic in the camera if you want. The important thing is background upload of photos as they are taken, like Google Photos does. Everything else is less important!

**Comment by natanlao** [comment]
Want to add a +1 here and say that I would even be fine *without* background sync -- just having the ability to manually kick off photo sync would be a game changer, since there's no easy way to do that right now.

I've toyed around with getting something set up with the Shortcuts app but wasn't able to get anything working.

**Comment by natanlao** [comment]
For those interested, I found a way to synchronize photos using Mobius Sync by using PhotoSync to automatically copy my photos to the Syncthing folder on my device. I've written more about it [here](https://gist.github.com/natanlao/04aba3245aeff4d01a0a5a77e71353c1).

**Comment by dm9tr0** [comment]
Any news? Does anybody will implement this? Also switched from Android and very like Syncthing for years.

**Comment by timdonovanuk** [comment]
Yes, I just revisited this app after 6 months, still no photo upload is a killer 👎

**Comment by philippzagar** [comment]
Would also be really interested in seeing that feature implemented!

**Comment by TehShrike** [comment]
I'm also looking for background photo syncing so that I can finally switch away from Dropbox.

Also: you should change from one-time payment for 4.99 to a yearly subscription for 4.99 or 9.99 – syncing photos from my phone to my computers is a load-bearing piece of my digital life, I don't want to rely on an app that's going to disappear in a few years because I'm not paying for upkeep.

**Comment by superkeyor** [comment]
Need camera upload! Also, if there are options allowing rename pattern (2021-12-22-10-18-31.jpg), that would be great!

**Comment by dm9tr0** [comment]
Nobody replied, nobody supported, but somebody wanted money for usage. 
Removed, asked refund and forgot. PhotoSync + Automation commands covered all my cases.

**Comment by TCB13** [comment]
+1 on this!

**Comment by Taxyovio** [comment]
> I'm also looking for background photo syncing so that I can finally switch away from Dropbox.
> 
> Also: you should change from one-time payment for 4.99 to a yearly subscription for 4.99 or 9.99 – syncing photos from my phone to my computers is a load-bearing piece of my digital life, I don't want to rely on an app that's going to disappear in a few years because I'm not paying for upkeep.

In this case you can directly donate your money to them. You’re saying “I like this so much so please everybody pays up.” You’re suggesting to lock the app up behind higher paywalls so you alone can enjoy it long term. Don’t suggest something on all other customers’s bearings. 

Literally everyone except you and greedy corporations hates subscriptions. It would be such a shame if Mobius Sync does adopt this despite being the spin-off from the FOSS community.

**Comment by TCB13** [comment]
> Also: you should change from one-time payment for 4.99 to a yearly subscription for 4.99 or 9.99

And that's how you kill an app. I would be okay with paying a one time fee for this feature not some monthly thing.

**Comment by TehShrike** [comment]
If they want to run an app as a charity project with donations, that's fine.

However, I can't switch away from Dropbox until I find something I can count on being maintained for the next 20 years.  And I know I can't expect that from a niche iOS app unless I pay for it.

**Comment by textpain** [comment]
Amazing feature. This is the only thing now preventing me from leaving iCloud. Any progress on this?

**Comment by mnakama** [comment]
I was about to buy premium, but then I saw that it doesn't sync photos. I have no use for file sync. I can't imagine why anyone would want file sync but not photo sync.

It looks like it's kind of on the roadmap, based on the official FAQ? But without any update or timeline after 1.5 years, it seems unlikely that it's being worked on. Photo sync on syncthing is easily worth $20 to me.

And they probably should try to keep it a one-time purchase. Since the end-user provides his own servers and bandwidth, an ongoing subscription fee would be a bit much for most people.

**Comment by tlaurion** [comment]
@sjpickup timeline for development of this feature?

**Comment by lpil** [comment]
Hi folks! Very excited for this feature 💜 

Is there a work-around in the meantime?

**Comment by Taxyovio** [comment]
> Hi folks! Very excited for this feature 💜
> 
> Is there a work-around in the meantime?

[PhotoSync](https://apps.apple.com/gb/app/photosync-transfer-photos/id415850124) is a possible (but a bit costly) workaround with the recent ability in Mobius to sync external folders.

**Comment by jdarpinian** [comment]
I have used PhotoSync with Mobius for a long time and it works. But
PhotoSync is expensive and background sync is not super reliable so I still
really want this feature in Mobius Sync.

**Comment by lpil** [comment]
I'm current trying to use the Shortcuts app to copy all photos from the last week into a folder to be synced by Mobius, and run that Shortcut daily. Haven't got it working yet, but it seems like it could!

Anyone tried something like this?

**Comment by andreasnyc** [comment]
**How does the Google Photos iOS app access the camera roll as well as do background sync of photos if non-system apps can't 1) access the camera roll,** 2) sync reliably in the background? Mainly I'm trying to point to the first part as no one seems to have mentioned the very-non-Apple iOS app Google Photos is happily accessing the camera roll.

I'm another recent Android user and I was happily using syncthing with 2-way sync to sync files from my main android phone to my Pixel 1 XL for unlimited free photo storage. The Pixel 1 has Google Photos set to backup and periodically it frees up storage and the local photo/video deletes would propagate back to my main phone. If I purposely deleted unwanted photos I just took on my main phone, that would get propagated to the Pixel 1 and they'd get deleted in Google Photos too. Perfect. I actually had the same from my android tablet.

Now I can't. I'd be very very happy to figure out how to make this work.

**Comment by RandomModderJDK** [comment]
Even though this is made with Flutter or Dart to be more specific. This could maybe help: https://github.com/immich-app/immich/tree/main/mobile

**Comment by alfredonodo** [comment]
Hi,
do you have any update on this?
Thank you

**Comment by SimonPickup** [comment]
I have been working on this for the past few weeks and I have got a good prototype going. Look out for it appearing on TestFlight shortly after we get v1.27.8 out.

There is no plan to charge a subscription since we're not providing a service!

**Comment by egigoka** [comment]
> I have been working on this for the past few weeks and I have got a good prototype going. Look out for it appearing on TestFlight shortly after we get v1.27.8 out.
> 
> 
> 
> There is no plan to charge a subscription since we're not providing a service!

You still spending $99/year tho. And your time isn't free also. 

I'd rather pay subscription than seeing you drop this project.

**Comment by SimonPickup** [comment]
To try the first alpha version supporting photo upload, and to discuss further, please see #172.
