### ISSUE TITLE
Support file tags

### ISSUE THREAD

**Issue by ghost** [MobiusSync/MobiusSync#41]
The main thing that has kept me from using syncthing is the lack of an iOS client. Now it's here, thank you. However, a few issues remain that make me doubt it's worth the switch. One of them is the lack of support for file tags (https://github.com/syncthing/syncthing/issues/2698).  Perhaps now that more effort is being spent on the Apple ecosystem through Möbius, there would be an incentive to add tag support to Möbius itself and the syncthing core?

(The other issue that I am so far aware of is no dot files in Möbius https://github.com/MobiusSync/MobiusSync/issues/26. Perhaps there are more, but I can't test enough with the 20MB limit and current limitations don't yet encourage to pay to remove it.)

**Comment by SimonPickup** [comment]
We'd consider adding this to Möbius Sync if it's ever added to Syncthing core, but doesn't look like it's getting much focus there. Please reopen if this is ever addressed in Syncthing core.

**Comment by 497e0bdf29873** [comment]
I just noticed that SyncThing now supports extended attributes. Syncing tags between macOS devices seems to sort of work if you allow `com.apple.metadata:_kMDItemUserTags` to be synced. (There are some issues, though, the most obvious is that proper synchronisation of tags would require SyncThing to understand the contents of that attribute. Also, the attributes don't seem to always sync, and there are some permissions issues.)

However, enabling the syncing of that attribute on iOS devices does not seem to do anything. So does iOS use something else for the tags, or does MobiusSync somehow (inadvertently) disable the feature?
