### ISSUE TITLE
Please make a full version without in-app purchase for EMM-support

### ISSUE THREAD

**Issue by stultitiophobia** [MobiusSync/MobiusSync#43]
Since we have no possibility to rule out in-app purchases with our EMM system it would be great to have a full featured version without in-apps.

**Comment by SimonPickup** [comment]
This is under preparation. Expect it to be released with Syncthing 1.18.4 core in the second week of November.

**Comment by SimonPickup** [comment]
The existing (freemium) version 1.18.4 is now released. We will wait to make sure no major bugs surface in this before releasing paid-upfront version in a week or two.

**Comment by Taxyovio** [comment]
Is this still going to be released?

**Comment by SimonPickup** [comment]
This is now awaiting Apple approval for external TestFlight distribution. A link will be provided here once available.

**Comment by SimonPickup** [comment]
Now in beta. For instructions on trying it out via TestFlight, see #97
