### ISSUE TITLE
Purchase button does nothing

### ISSUE THREAD

**Issue by yughcnerfyrgna** [MobiusSync/MobiusSync#46]
Would lile to give you money but purchase tab design flaw males it impossible on iPhone 7 14.6.

Entire menu unclickable. Freezes app.

![EBB13A18-A61D-4AD3-A9F0-C127A1F00020](https://user-images.githubusercontent.com/17603054/124839053-0b052480-df56-11eb-9819-70a21d80ddc9.png)

**Comment by maxmenGMK** [comment]
I can’t to purchase it too. When I touch the “purchase” button there nothing happens at all. iPhone 7+, IOS14.6

**Comment by yughcnerfyrgna** [comment]
Solved. Thank you!

**Comment by maxmenGMK** [comment]
> Solved. Thank you!
I check it right now and the problem still there.

**Comment by vEnhance** [comment]
I am experiencing the same issue as @maxmenGMK on iOS 15.0.1, iPhone Xs, where the "purchase" button has no effect whatsoever.

**Comment by SimonPickup** [comment]
Sorry @maxmenGMK, I missed this since the issue had been closed.

To you and @vEnhance and anyone else with this problem.. do you mean you see nothing when you click on the Purchase item in the menu (i.e. the first item, above Settings and Show ID... or are you seeing the popup (similar to the screenshot at the start of this issue)?

Also please advise which country app store you are using (and whether you use multiple app store logins on that device).

**Comment by vEnhance** [comment]
> do you mean you see nothing when you click on the Purchase item in the menu (i.e. the first item, above Settings and Show ID... or are you seeing the popup (similar to the screenshot at the start of this issue)?

The former, nothing at all appears upon clicking Purchase (it just closes the menu), and nothing appears in the log file as far as I can tell. I'm in the United States with just a single login. The error persists regardless of whether the iPhone is connected to iCloud or not.

Interestingly, it works perfectly on my iOS14 iPad Pro.

**Comment by SimonPickup** [comment]
> Interestingly, it works perfectly on my iOS14 iPad Pro.

What does Restore Purchases do?

**Comment by vEnhance** [comment]
I can't find a "Restore Purchases" button, where should I be looking?

**Comment by 497e0bdf29873** [comment]
The problem seems to be related with the dialog not getting the “focus”.  Scrolling up and down still moves the main SyncThing web page in the background. I had the buttons appear properly unlike the screenshot above, but they didn't do anything until I restarted the app.

**Comment by flipjs** [comment]
I have this issue on my iPad Pro (ipadOS 15.6) and iPhone 8 Plus (iOS 15.6) too. The screenshot on the original post is exactly the same Im seeing. All clicks on any part of the screen is not doing anything.
I have another device which is iPhone 13 Mini (15.6), this one the dialog box renders fine and was able to purchase it.
Hope this can be fixed so I can sync on multiple apple devices. Thanks.

**Comment by madeinoz67** [comment]
Same on iPad Pro, no response to any where on screen

![image](https://user-images.githubusercontent.com/4160293/186449108-a5b6f3fd-b28f-408d-8f23-4acf91f08a3a.jpeg)

**Comment by SimonPickup** [comment]
A clever user has worked out that this happens on devices where the iOS text size has been changed. See details here: #94.

With that hint we'll also be able to fix it in the software.

**Comment by SimonPickup** [comment]
Fix going to TestFlight.
