### ISSUE TITLE
Encrypted folders unsyncable due to no password input

### ISSUE THREAD

**Issue by anijatsu** [MobiusSync/MobiusSync#47]
The application doesn't show a password input under Sharing tab in folder settings.

v1.13.1-18-gda627a78-i1.3, iOS (64-bit ARM) 
"Fermium Flea"
Build 202102091720
running on iPhone SE 2016

![C71A43DA-0F27-4E1F-8589-C3B69B841308](https://user-images.githubusercontent.com/1882015/126065499-c86b765f-e825-47ae-a9fc-058502d1f7f9.jpeg)
![805A4B7C-43A0-4C47-871A-D097B46C9A9F](https://user-images.githubusercontent.com/1882015/126065501-fa33f43a-72f3-4907-8c30-81fcfd0a78d8.jpeg)

**Comment by yughcnerfyrgna** [comment]
bump

**Comment by SimonPickup** [comment]
This is becuase Syncthing core is currently 1.13.1, which doesn't support encryption. We are working on bringing the latest Syncthing core into MöbiusSync, in issue #49.

**Comment by SimonPickup** [comment]
Currently under beta testing.
