### ISSUE TITLE
Can't reconsider getting notifications

### ISSUE THREAD

**Issue by adiabatic** [MobiusSync/MobiusSync#48]
When I first ran Möbius Sync, it prompted me to turn on notifications and also let it scan my local network. I let it scan my local network, but like for most apps, I didn't even let it ask to send notifications.

After seeing how weird and wild background processing is on iOS (I had _some_ idea, but I care about timely syncs for Syncthing sometimes unlike for other apps), I thought it might be nice to get notifications for Möbius Sync. However, when I go to the Möbius Sync page in Settings, I only see:

- Local Network [on]
- Siri and Search [>]
- Background App Refresh [on]
- Cellular Data [off]

(I turned Cellular Data off after skimming the FAQ)

I don't see a way to get back to the initial-setup screen where I can nudge Möbius Sync into goading the system to ask me if I want to turn notifications on. Is there?

**Comment by dancojocaru2000** [comment]
Don't go to the Mobius Sync page, go to the Notifications page.

**Comment by adiabatic** [comment]
It's not in there either, though:

![IMG_3091](https://user-images.githubusercontent.com/101246/133710636-1fab1dcf-1ac7-4372-888a-f642d58928d0.PNG)

**Comment by rasa** [comment]
I see Mobius Sync on my Notification page on iOS 14.7.1. Perhaps uninstall and reinstall?
![0AF5A1DF-B426-42E9-89D6-B15469D8D89E](https://user-images.githubusercontent.com/220772/133723184-00ba0629-91f3-45bf-b539-a8653eed5920.jpeg)

**Comment by adiabatic** [comment]
If I do that, will I dump all the files it's stored and have to re-download them?

**Comment by dancojocaru2000** [comment]
@adiabatic Maybe?

You could copy the stuff using the Files app, and then put them back after reinstalling so they don't have to be downloaded again.

**Comment by adiabatic** [comment]
I reinstalled the app and re-set up its connections with other computers. The workaround, unsurprisingly, worked, and now I can see all of Möbius Sync's notifications.

**Comment by dancojocaru2000** [comment]
That's great to hear! You could probably close this issue then.
