### ISSUE TITLE
Disable "External File Versioning" as it does not make sense on iOS

### ISSUE THREAD

**Issue by SimonPickup** [MobiusSync/MobiusSync#58]
The Syncthing "External File Versioning" strategy (see https://docs.syncthing.net/users/versioning.html) invokes a user-provided external command, which does not make sense on iOS. Hence this option should be removed.

**Comment by SimonPickup** [comment]
Beta in TestFlight now.

**Comment by berkan** [comment]
Hello, 

Thank you for Mobius Sync, it is an essential feature of my everyday workflow.

I wonder if you'd consider enabling the "External File Versioning" feature again.

Specifically, could you please allow Mobius to call a (customisable) iOS Shortcut as the ["external command"](https://docs.syncthing.net/users/versioning.html#external-file-versioning) of External File Versioning strategy?

A possible way to utilise this is the following setup:

An open-source iOS application called [a-Shell](https://holzschu.github.io/a-Shell_iOS/) has Shortcuts integration, which allows programmatically triggering shell scripts to run.

a-Shell also supports opening folders in other app sandboxes (eg, any folder synced by Mobious Sync).

These, together with a-Shell's [libgit2](https://libgit2.org/) integration, means it may be possible to have a setup where a git-based (external) versioning strategy can be used in Mobius Sync:

- We set up a-Shell to access one or more folders synced by Mobius Sync, and initialise them as git repositories. 
- When Mobius Sync needs to version a file (eg an updated version has arrived), it can now call the custom Shortcut with the FOLDER_PATH and FILE_PATH arguments as per the External File Versioning strategy
- This Shortcut triggers an a-Shell script with the said arguments
- The a-Shell script uses libgit2 to commit the new version of the file

There are other possible setups, based on other git apps (eg Working Copy), as well as taking other versioning actions not based on git. 

As I understand it, all that is missing for this setup is for Mobius to re-enable the External File Versioning, with the  ability to call a Shortcut.

Does this make sense? Is this something you could look into and consider adding to Mobius Sync?

Many thanks again,
Berkan
