### ISSUE TITLE
Sync files outside app sandbox

### ISSUE THREAD

**Issue by SimonPickup** [MobiusSync/MobiusSync#59]
It should be possible for the user to allow specific permissions for MobiusSync to sync other app's sandboxes. See https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories

This is done by a-shell, for example: https://github.com/holzschu/a-shell#sandbox-and-bookmarks

It looks like each individual file/folder access operation must be wrapped by calls to access a "security-scoped URL" so this will involve deep changes in the Syncthing core, i.e. will be non-trivial and hard to maintain.

**Comment by emillienemann** [comment]
Yeah, really needing this to sync an app's folder over to SyncThing.

**Comment by johannrichard** [comment]
Allow me a thought: from going through the Swift documentation for `startAccessingSecurityScopedResource()`, and some examples here and there e.g. https://stackoverflow.com/questions/67438641/how-to-access-a-security-scoped-resource-from-a-string-path-in-swift), and obviously knowing nothing about your code, I was wondering whether it would not be sufficient to wrap the existing access based on your modified syncthing's "standard means" (i.e. what you presumably already do in MöbiusSync) for files outside the sandbox with calls to `startAccessingSecurityScopedResource()` and `stopAccessingSecurityScopedResource()` for a bookmark pointing to the respective root folder which was selected upon setting-up the sync folder? I understand the documentation/examples such as that once the resource (root directory) is made accessible to the iOS program during a session, files and folders within this resource will also be accessible to the program, without necessarily start/stopping for each file and subfolder individually.

> ### startAccessingSecurityScopedResource
> Given a url created by resolving a bookmark data created with security scope, make the resource referenced by the url accessible to the process.

**Comment by emillienemann** [comment]
> Yeah, really needing this to sync an app's folder over to SyncThing.

I fixed this by using Working Copy to open the app folder as repository and syncing it to Möbius.

**Comment by rasa** [comment]
It appears [a-shell](https://holzschu.github.io/a-Shell_iOS/) offers its users access to other apps folders. See https://github.com/holzschu/a-Shell#sandbox-and-bookmarks for a short write-up, and https://github.com/holzschu/a-shell/search?q=pickfolder for the Swift source code.

**Comment by ghost** [comment]
Hope this feature is included soon. iSH https://github.com/ish-app/ish also allow this with the mount command.

**Comment by AlJohri** [comment]
This would be really helpful for me as well to be able to use with Logseq https://logseq.com/.

Logseq only works with the files in its container or iCloud Drive so I would like to use MobiusSync for either of those locations.

**Comment by tingqin01** [comment]
> This would be really helpful for me as well to be able to use with Logseq https://logseq.com/.
> 
> Logseq only works with the files in its container or iCloud Drive so I would like to use MobiusSync for either of those locations.

Me too. I bought it and found it didn't work

**Comment by berot3** [comment]
Is this at least on the roadmap with a somehow higher prio?
IMHO this is a essential feature. 

Really needing this for my notes (https://github.com/obsidianmd)

**Comment by carvey** [comment]
Any update on this? Or need any help with implementation? Agreed this would be fantastic to have.

**Comment by cable729** [comment]
I also need this for LogSeq. Is anyone still working on this project?

**Comment by kuzzmi** [comment]
Planned to migrate my notetaking flow to Obsidian and found this limitation. The most confusing thing is that many other iOS apps work with files/folders outside their sandbox, so that should be possible and, as I can see, is being requested for a long time.

**Comment by Riz0** [comment]
@sjpickup @pvinis Any good news on this front? Like others here, I want to use this with a note taking app and am unable to select any folder outside the app's sandbox.

**Comment by Doc-Steve** [comment]
@sjpickup @pvinis I think this feature is the most important to enhance usability on iOS. This app could then used for soooo much more, e.g. syncing your movies to the VNC app, sync folders to Goodreader ... endless possibilities.

Could you give any feedback if/when this may be implemented?

If you tell me how to donate for this or if you decide you make it an extra in-app purchase, me and I think many others would love to spend this extra money 😀

**Comment by mbode** [comment]
> I fixed this by using Working Copy to open the app folder as repository and syncing it to Möbius.

@emillienemann Could you share a few details on how Working Copy can be used as a bridge between Möbius and a 3rd app?

**Comment by blakekl** [comment]
This should be the way the tool works. Would make it so much easier. I have the app I want to syncs folder structure recreated on möbius now and have to manually copy files around to get updates in the apps. This should just be automatic. Mobius isn’t nearly as useful without this.

**Comment by hvddrift** [comment]
> > I fixed this by using Working Copy to open the app folder as repository and syncing it to Möbius.
> 
> @emillienemann Could you share a few details on how Working Copy can be used as a bridge between Möbius and a 3rd app?

@emillienemann I would be interested in how you did this also.

**Comment by emillienemann** [comment]
> > > I fixed this by using Working Copy to open the app folder as repository and syncing it to Möbius.
> > 
> > 
> > @emillienemann Could you share a few details on how Working Copy can be used as a bridge between Möbius and a 3rd app?
> 
> @emillienemann I would be interested in how you did this also.

It's pretty simple. Just press the + in Working Copy and tap "Open external directory". Once you've opened the external folder, tap the name of the folder and "Setup Sync" -> "Directory" to Möbius.
The obvious disadvantage is that you'll always have to open Working Copy for it to sync.

**Comment by ghost** [comment]
Is there any progress on this feature?

**Comment by SimonPickup** [comment]
First **EXPERIMENTAL** support for this is now out in TestFlight build 202302190945. Please use at your own risk and report successes and problems in this thread. See #97 for details on joining TestFlight.

Choose another app's folder using the "Pick Folder" button when adding a new folder. You will be warned that you are proceeding at your own risk.

Note that you **cannot** select the top-level _On My iPhone_ or _On My iPad_ folder, nor can you select _iCloud Drive_. Not sure if this possible through the iOS security-scoped URL mechanism.

**Comment by johannrichard** [comment]
Simon, thank you so much for this feature! This is really great news and much appreciated. 😊

**Comment by rasa** [comment]
I just tested sharing my Acrobat folder between two iPads running build 202302190945 and it works like a charm. Right now, one's Send Only, and the other's Receive Only, but will test Send And Receive soon. 

Originally, the receiving ipad had a "Local Additions" that the Files app couldn't see (named inbox/something), but I clicked "Revert Local Changes", and the warning disappeared. This was probably some random hidden file that Acrobat created.

**Comment by johannrichard** [comment]
Did some experimentation with syncing an Obsidian Vault. Changes seem to be picked up reliably and quickly so far. 👾 🙇🏽

**Comment by SimonPickup** [comment]
I have noticed some cases where folders outside the sandbox "lose access" after a day or so, with an _operation not permitted_ error. Haven't been able to work out a pattern yet. Anyone else seen this?

In most cases, you can edit the folder and use Pick Folder to select the correct destination again, which requests fresh access.. however this should not be necessary.

**Comment by rasa** [comment]
@sjpickup While I am successfully syncing files, and haven't "lost access", I am finding a few issues:
1. On an existing folder, and even though the "Folder Path" is grayed out, clicking the "Pick Folder" button allows me to change the folder path. It's my understanding the only way you can change the Folder Path, is to stop the Syncthing daemon, and edit the config file manually. ~~Best to disable (or remove) the "Pick Folder" button on existing folders.~~ Best to not allow the user to change the folder path on existing folders.
2. After creating a folder, and then clicking "Open Folder", the folder shown is whatever folder the Files app is currently displaying (such as my Chrome folder), and not the Acrobat folder I selected originally.
3. Even though both devices are syncing 12 files in the sender's Acrobat folder, both sender and receiver show a Global State of 42 files and 3 folders (which are the contents of my Chrome folder, which is the next folder in the "On My iPad" list).
4. When I created a new folder, I switched to the "Advanced" tab, and switched the Folder Type to "Send Only." When I did this, the UI automatically checked the "Watch for Changes" checkbox. I didn't notice this, and clicked "Save", and later saw this message:

![1A6A8500-19E5-43CD-AFE5-A5E1D08A7995](https://user-images.githubusercontent.com/220772/220201852-3956b0de-7875-4669-9342-477357bc730c.jpeg)

I have seen these issues on the first folder I created, and again after deleting that folder, and sharing the Acrobat folder again, using a different folder ID.

**Comment by SimonPickup** [comment]
Thanks for your great feedback, @rasa.

> 1. On an existing folder, and even though the "Folder Path" is grayed out, clicking the "Pick Folder" button allows me to change the folder path. It's my understanding the only way you can change the Folder Path, is to stop the Syncthing daemon, and edit the config file manually. ~Best to disable (or remove) the "Pick Folder" button on existing folders.~ Best to not allow the user to change the folder path on existing folders.

Yes, this is the mechanism I used to "refresh access" to a folder which has lost access. But I realise it is very dangerous if you choose a different folder and needs to be restricted/disabled before public release.

> 2. After creating a folder, and then clicking "Open Folder", the folder shown is whatever folder the Files app is currently displaying (such as my Chrome folder), and not the Acrobat folder I selected originally.

Yes, I was aware of that too. Whilst I can ask iOS to open the Files app within a subfolder of the Möbius Sync  sandbox, it doesn't seem possible to do so for an "external" folder. I'll probably just remove that button for "external" folders, but it's less than ideal.

> 3. Even though both devices are syncing 12 files in the sender's Acrobat folder, both sender and receiver show a Global State of 42 files and 3 folders (which are the contents of my Chrome folder, which is the next folder in the "On My iPad" list).

That is extremely odd, and I'm pretty sure mine haven't been doing that, but I'll keep an eye open for that. I can't imagine how my changes could have triggered such a bug, so I'm wondering if it's an existing syncthing problem just exposed here by chance.

> 4. When I created a new folder, I switched to the "Advanced" tab, and switched the Folder Type to "Send Only." When I did this, the UI automatically checked the "Watch for Changes" checkbox. I didn't notice this, and clicked "Save", and later saw this message:

I'm pretty sure that would happen also for an "internal" folder (within the Möbius Sync sandbox). I've been thinking for a while that I really should completely disable Watch for Changes, as it doesn't make sense in Möbius Sync.

Another minor issue I'm aware of is that when adding a new folder if you _Pick Folder_ first, then type in a _Folder Label_, the label overwrites the previously-chosen folder path.

**Comment by johannrichard** [comment]
I ended up with this warning with the Obsidian Vault after two days of not using that iPad (was probably not connected to the Network at all). I assume it's MöbiusSync losing access / permission to the folder. 

![IMG_B307F1F4D66C-1](https://user-images.githubusercontent.com/189003/220449291-cd7a8a7c-5eb8-49d6-b9d2-4a146c713052.jpeg)

On another iOS device where I had the app running in the background more regularly, I did not yet run into that one.

Re-selecting the original folder I originally synced with did resolve the problem (i.e. the "Pick Folder" mentioned above was working). I would assume a more robust way to keep the permissions would be needed if the "Pick Folder" was to be disabled once it's set?

Addendum: On another iOS Device, I got the same warning, followed by a different error when trying to re-select the folder with "Pick Folder" or change the ignore pattern. Here, I had to remove the folder in MöbiusSync and re-add it again. When removing it from Möbius, the error appeared as well, and in any case, I had to force-quit MöbiusSync.

![IMG_E35CABFFDDF8-1](https://user-images.githubusercontent.com/189003/220453023-897862fd-5afa-45e1-812c-7f35cc30ac92.jpeg)

**Comment by rasa** [comment]
@sjpickup Yes, 3. is most likely a Syncthing bug, or a database corruption issue.

Re 4., I agree that disabling "watch for changes" in iOS makes the most sense, as most users won't understand that cryptic error message.

**Comment by johannrichard** [comment]
I ended up with yet another warning /error when the App (Obsidian) whose folder I'd linked to in MöbiusSync was updated. 

When I re-picked to folder, the UUID of the Application changed and everything worked again. 

![image](https://user-images.githubusercontent.com/189003/220841222-5f55234a-d3d6-4922-82a7-2a93d0132651.jpeg)

To be noted that I use a TestFlight build here, so I can't tell whether these UUIDs are supposed to be stable for "regular" apps.

**Comment by johannrichard** [comment]
Simon, 

> To be noted that I use a TestFlight build here, so I can't tell whether these UUIDs are supposed to be stable for "regular" apps. 

I'm no expert here re:iOS but could it be there's something amiss with how MöbiusSync currently keeps track of [the security scoped URLs?](https://developer.apple.com/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso#working-with-bookmark-data)

**Comment by SimonPickup** [comment]
Thanks all for the feedback. Please keep it coming. I do have another idea to try, probably can't do it until the weekend though.

**Comment by SimonPickup** [comment]
New TestFlight build 202302241713 is now available for both Pro and Freemium variants. It hopefully fixes the problem of disappearing permissions. **Still highly experimental - continue to use at your own risk.**

**Comment by johannrichard** [comment]
> New TestFlight build 202302241713 is now available for both Pro and Freemium variants. It hopefully fixes the problem of disappearing permissions. 

Happy to confirm that it works with the new bookmark based approach. It even seems to survive an app (Obsidian) update, but will observe a few more Obsidian beta updates to be sure. 

One thing (obvious one): with the way of storing the bookmark, any information about the folder we link to gets lost (i.e. name on disk). I'm not sure how to feel about thatcher, at first sight I was missing the certainty to know I linked to the right folder. 

But I also understand it could be difficult to retrieve the linked-to app and it's folder once it's been selected?

**Comment by SimonPickup** [comment]
> > New TestFlight build 202302241713 is now available for both Pro and Freemium variants. It hopefully fixes the problem of disappearing permissions.
> 
> One thing (obvious one): with the way of storing the bookmark, any information about the folder we link to gets lost (i.e. name on disk). I'm not sure how to feel about thatcher, at first sight I was missing the certainty to know I linked to the right folder.

Yeah it "hurt" me too, but the full path is meaningless too, right? i.e. no concrete reason to display the actual full path?

**Comment by johannrichard** [comment]
> [...] but the full path is meaningless too, right? i.e. no concrete reason to display the actual full path?

Agree on that, the context is missing and thus it's not really useful. 

Just a thought: Another way could be to display with a Document Picker (in the app) the folder where the bookmark points to. I understand the [UIDocumentPickerViewController](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller) accepts a directoryUrl as an argument – could that be used to "Show Folder" (instead of "Pick Folder") once the local folder has been set? 

Of course this might add new UI problems as there's probably no way to make it clear in the Document Picker that nothing will happen if a different folder is selected by the user.

**Comment by SimonPickup** [comment]
New TestFlight build 202302270457 is now available for both Pro and Freemium variants:

- I worked out how to get "Open Folder" working appropriately. I have also renamed the button to "Pick External Folder" and added some better help text.
- Set up external app sync as a paid feature, so on the Freemium variant, you will get the in-app purchase dialog when pressing "Pick External Folder" unless already paid.
- There is now an alert if you have both Pro and Freemium versions installed simultaneously.
- The file watcher is now completely disabled on iOS so there will be a more meaningful error message if it is accidentally turned on (e.g. when setting a folder to "Receive Only". (A later step would be to remove the ability to even request it in the GUI.)
- The top-level "Open Folders" button is now "Open Files App". It currently opens at the last folder you visited. I haven't worked out how to force it to go to a top-level folder, e.g. "On My iPhone" yet.

As far as I'm aware, this is now ready to release, so hope to do so within a few days unless any strong negative feedback.

**Comment by johannrichard** [comment]
Thanks for that new build, that are some good news.

> I worked out how to get "Open Folder" working appropriately. I have also renamed the button to "Pick External Folder" and added some better help text.

Great, that solves the problem of "where did I sync to" of sandboxed folders (and much better than my convoluted proposal. :-))

**Comment by wojciech-kulik** [comment]
Hi, i’m looking for a solution to sync Dropbox file from the Files app, but it seems like it’s not possible to request the synchronization and after the initial read I always get the same content unless I explicitly open Files app and go to its location to sync.

By any chance, have you solved this issue?
