### ISSUE TITLE
QR scanner to add remote device

### ISSUE THREAD

**Issue by sjpickup** [MobiusSync/MobiusSync#6]
Placeholder issue. Detail to be added. Please like (and ideally comment) if you want this feature.

**Comment by YellowSloth** [comment]
During setup it would be very useful to be able to scan the QR code on the computer screen. Especially considering that computers don't always have cameras.

**Comment by sjpickup** [comment]
Yeah, I'm surprised it's not already in Syncthing itself. We will try to contribute to the core code-base if it can be done generically.

**Comment by sjpickup** [comment]
It looks like generic HTML5 solutions are not mature enough on iOS yet (see https://github.com/mebjas/html5-qrcode/issues/14) so I have implemented a native iOS solution for now.
