### ISSUE TITLE
Doesn't recreate/re-sync deleted files folders on iOS even when "receive" is enabled

### ISSUE THREAD

**Issue by amarendra** [MobiusSync/MobiusSync#60]
The folder, let's call it `backup` folder, on Mac is set to "Send Only".

Same folder on iOS/Mobius is set to "Receive Only".

I delete synced files/folders on iOS inside `backup`. 

Those files and folders don't get synced/recreated again as it happens with two instances of Syncthing between two computers.

**Comment by SimonPickup** [comment]
As a guess this may be because file watcher is disabled in iOS. Does a rescan force a recreation?
