### ISSUE TITLE
Synced folder location

### ISSUE THREAD

**Issue by julienpmorand** [MobiusSync/MobiusSync#67]
Hi, there seems to be an issue with my new install; whenever I add a folder (either locally or added through another device), I can specify the path (path is prepended with `./`), but if I check in the Files App, I cannot see the folder anywhere. I checked in all the directories. If I click on the "Open Folder" button from the app, it opens the File app at the last location it was already open, so it doesn't reveal the folder location.

In the Settings app, I checked the Möbius Sync settings and I got
* Siri & Search
* Notifications
* Background App Refresh
* Cellular Data

I also checked the privacy settings of the Files app and the only app listed that has access to the Files is Photos. Möbius Sync never prompted me to grant it permissions to the Files app.

Running iOs 15.2.1 on an iPhone 11

Any help would be appreciated

**Comment by steefdebruijn** [comment]
Same problem here. Syncs fine but where to??? Can't find anything in files app.

* iPhone 13 Pro Max 
* iOS 15.3.1
* Mobius v1.18.4-31-g92f42768d-i, iOS (64-bit ARM)

**Comment by steefdebruijn** [comment]
Follow-up: I just updated to iOS 15.4 and the synced files appeared in Files app. 
I do not know if the upgrade did the trick, or the device reboot after it.

HTH,
Steef

**Comment by Stooovie** [comment]
On iOS 16.1 beta, I don't see the synced files. Where are they supposed to be? They're not in iCloud nor in the On this phone folder. 

Edit: oh, after rebooting the phone it's in On this phone.
