### ISSUE TITLE
Application not available in App Store

### ISSUE THREAD

**Issue by lauhub** [MobiusSync/MobiusSync#69]
Hi,

I live in France and I would like to use your application. However, it is not possible to download it because it is not available in french store.

Could you do something ?

**Comment by NatHarari** [comment]
I literally came here to say the same thing. Could you please make it available in France? Thanks!

**Comment by jcaude** [comment]
okay, same here .. that's a shame as it would be a winning replacement for Synology drive that doesn't support offline browsing..

**Comment by NatHarari** [comment]
> okay, same here .. that's a shame as it would be a winning replacement for Synology drive that doesn't support offline browsing..

Yeah, I’m surprised there’s no answer at all either, considering it’s not an abandoned project from what I can tell.

**Comment by SimonPickup** [comment]
Duplicate of https://github.com/MobiusSync/MobiusSync/issues/27
