### ISSUE TITLE
On IPad unzipped folders don’t get synced 

### ISSUE THREAD

**Issue by 404LengiNotFound** [MobiusSync/MobiusSync#70]
First of all thanks for this great application over all it does exactly what I need it for

I just recently noticed that it will not sync folders and their contents when they where created by one click extraction with the IPad files Application 

I couldn’t find anyone else mentioning this problem in the forum here so maybe it is a configuration issue on my side but I extensively checked weather that is the case and I don’t think so

I’m running the latest Möbius Sync Version (Full Version)
On IPad OS 15.0.2

**Comment by SimonPickup** [comment]
@404LengiNotFound, are you talking about extracting Zip files, as described at https://support.apple.com/en-gb/HT211132 ?

**Comment by 404LengiNotFound** [comment]
Yes

**Comment by 404LengiNotFound** [comment]
Update:
After I encountered some other weird behavior, where just pdf files downloaded originally on my IPad didn't show on my computer, I did a bin more experimentation and relized that the issue is actually not with Möbius synch but with my smb server on my NAS / Windows file system in general it seems really doesn't like files or folders created under IOS

**Comment by tnwjd3315** [comment]
Wow it helped me alot, thank you dude

**Comment by tnwjd3315** [comment]
> Update: After I encountered some other weird behavior, where just pdf files downloaded originally on my IPad didn't show on my computer, I did a bin more experimentation and relized that the issue is actually not with Möbius synch but with my smb server on my NAS / Windows file system in general it seems really doesn't like files or folders created under IOS

haha
