### ISSUE TITLE
Purchase button is still broken

### ISSUE THREAD

**Issue by mike-scofield** [MobiusSync/MobiusSync#76]
I see an old issue along these lines here: https://github.com/MobiusSync/MobiusSync/issues/46

And I see that there was a plan to add a Paid version in the App Store, but I still don't see one: https://github.com/MobiusSync/MobiusSync/issues/43

I am on an iPad Air 4 running iOS 15.5.  If I click on Actions -> Purchase, literally nothing happens.

Is this app still under active development?  It seems like something that could be super useful but I'll never be able to evaluate it with the 20MB limit in place.

**Comment by SimonPickup** [comment]
There are many purchases per month, so it's unclear why it doesn't work for a few. The paid app as per #43 will be the likely workaround path. Closing as duplicate.
