### ISSUE TITLE
Issue with deleting files/folder in the MobiusSync folder

### ISSUE THREAD

**Issue by TAutoWelt** [MobiusSync/MobiusSync#81]
I have been using Mobius Sync for a while with no issues... until now, when I updated my iPhone to the new iOS 16.
Not sure if this was caused by the update but now I have problems deleting files from the MobiusSync folder using the native Files app on the iPhone. 
When I try to delete any file or folder i get the error from the screenshot. 
![IMG_3230](https://user-images.githubusercontent.com/114222005/191925512-2df1c919-ff39-4b2b-8020-306754a594aa.jpg)

This only happens in the Mobius Sync folder.
When I delete some files on another device that synchronizes with my iPhone the files are removed from the iPhone when MobiusSync process the synching. But I can't manually delete files from my iPhone.
I tried restarting the app, the phone but nothing changes. 

Looking forward for the solution of this issue,
Thanks

**Comment by SimonPickup** [comment]
I cannot reproduce this. Anyone else?

**Comment by CanadianEngineer** [comment]
I’m able to reproduce this issue on my device. iPad mini (6th generation), iOS 16.3.1, Mobius Build 202303072020.

These might be the steps to reproduce:

* Create a large folder on another device (in my case, it was my desktop running Linux with file versioning)
* Sync it with your mobile device (in try case, it’s my iPad)
* Once it has been downloaded, I didn’t do much with it for a few days. I might have modified a file or two on my iPad, but might have done a bit of work on other devices.
* Remove the folder from Mobius using the Mobius UI
* Go into Files on my iPad and delete the old folder
* Check the iPad storage info under settings.

Expected: The storage amount to be reduced

Actual: Settings still report a large amount of storage still in use

**Comment by SimonPickup** [comment]
This seems to be an iOS issue: https://www.macobserver.com/tips/how-to/fix-you-dont-have-permission-to-access-trash-iphone-and-ipad/
