### ISSUE TITLE
Incorrect issue based on a misunderstanding; ignore

### ISSUE THREAD

**Issue by calmh** [MobiusSync/MobiusSync#82]
In this FAQ entry it is claimed that "Pickup Infinity" is a corporate sponsor of the Syncthing project. This is a lie; Pickup Infinity is not a corporate sponsor nor have they ever been, and to my knowledge have never contributed either monetarily nor otherwise to the project.

<img width="782" alt="Screenshot 2022-10-03 at 11 09 27" src="https://user-images.githubusercontent.com/125426/193541422-6ae9d489-0b03-43a9-a1d3-963f0ecbae10.png">

**Comment by SimonPickup** [comment]
![image](https://user-images.githubusercontent.com/18005537/193543031-ebd5c223-5cde-448d-b8ff-2bda25563230.png)

We are listed as a sponsor on the GitHub page - second on this screenshot. Payments have been in place since November 2021. I hope you are indeed receiving the money @calmh.

**Comment by calmh** [comment]
This is true; I was looking in the wrong place. My apologies!

**Comment by rasa** [comment]
@calmh Could the title of this issue be edited for clarity?
