### ISSUE TITLE
Stopped – folder marker missing

### ISSUE THREAD

**Issue by scotmartin** [MobiusSync/MobiusSync#84]
I set up the folders and syncing worked both ways. An error was displayed when I opened it today and the folder stopped syncing.

`Error on folder "Sync" (sync) at ./Sync: folder marker missing (this indicates potential data loss, search docs/forum to get information about how to proceed) `

After reading issue #28 I purchased the full version (despite only syncing 10,4 MB). However, that did not solve the problem.

Searching the documentation I understand this error is displayed when the .stfolder marker is missing. However I cannot create it in the iOS files app because it starts with a dot (.)

**Comment by scotmartin** [comment]
I was able to get it working again following issue #26 and buying the FE Filemanager pro app to create the .stfolder from there.

**Comment by mbledkowski** [comment]
Please fix this. I do not want to buy yet another app

**Comment by joeysaladino** [comment]
For anyone else who comes across this and doesn't want to buy yet another paid app just to create a folder (like me), I was able to create the folder by modifying [this Siri shortcut](https://www.icloud.com/shortcuts/1bbe3e687e414ca39c14de027ed4068b) to create a .stfolder folder

This fixed the issue for me.

**Comment by SkyLeite** [comment]
Thanks @joeysaladino for the tip! I was able to modify the Siri shortcut to create the missing `.stfolder` in Logseq's sandbox.

Here it is in case anyone needs it in the future: https://www.icloud.com/shortcuts/be8f001a9aa149e1976d5a24a86136c9

Just add the shortcut, run it and select the folder when prompted. The shortcut will then create a folder called `.stfolder` inside it.
