### ISSUE TITLE
after setting user/password, no way to enter credentials, unauthorized screen

### ISSUE THREAD

**Issue by tcecyk** [MobiusSync/MobiusSync#88]
if a user/password is set on the admin panel, the webview will show white "unauthorized" screen with no way to enter the credential

**Comment by BigHomie90** [comment]
I have the exact same problem.

**Comment by SimonPickup** [comment]
This is a regression in v1.21.0. Will be fixed in upcoming v1.23.1.

Workaround is to delete and reinstall the app.
